services:
  # db:
  #   image: postgres:15
  #   container_name: graph_postgres_db
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #   volumes:
  #     - postgres_graph_data:/var/lib/postgresql/data/
  #   ports:
  #     - "5432:5432"
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: graph_fastapi_app
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL_APP_DOCKER}
      #DB_ALEMBIC_URL: ${DATABASE_URL_APP_DOCKER}
    # depends_on:
    #   db:
    #     condition: service_healthy

  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   container_name: graph_pgadmin
  #   restart: unless-stopped
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   volumes:
  #     - pgadmin_graph_data:/var/lib/pgadmin

volumes:
  postgres_graph_data:
  pgadmin_graph_data:
